// Approval Page Script
document.addEventListener('DOMContentLoaded', function() {
    // Get application data
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    
    if (!applicationData.loanAmount) {
        // If no data, use defaults or redirect
        console.warn('No application data found, using defaults');
    }
    
    // Get loan details
    const loanAmount = parseFloat(applicationData.loanAmount) || 5000; // Default 5M TSh
    const loanTerm = parseInt(applicationData.loanTerm) || 12;
    const annualRate = 0.12; // 12% APR
    const monthlyRate = annualRate / 12;
    
    // Calculate monthly payment
    const monthlyPayment = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, loanTerm) / 
                          (Math.pow(1 + monthlyRate, loanTerm) - 1);
    
    const totalRepayment = monthlyPayment * loanTerm;
    
    // Update display with correct IDs and Pcurrency
    const approvedAmountEl = document.getElementById('approvedAmount');
    const loanAmountDetailEl = document.getElementById('loanAmountDetail');
    const monthlyPaymentDetailEl = document.getElementById('monthlyPaymentDetail');
    const repaymentPeriodDetailEl = document.getElementById('repaymentPeriodDetail');
    const totalRepaymentDetailEl = document.getElementById('totalRepaymentDetail');
    
    if (approvedAmountEl) approvedAmountEl.textContent = '$' + loanAmount.toLocaleString();
    if (loanAmountDetailEl) loanAmountDetailEl.textContent = '$' + loanAmount.toLocaleString();
    if (monthlyPaymentDetailEl) monthlyPaymentDetailEl.textContent = '$' + Math.round(monthlyPayment).toLocaleString();
    if (repaymentPeriodDetailEl) repaymentPeriodDetailEl.textContent = loanTerm + ' months';
    if (totalRepaymentDetailEl) totalRepaymentDetailEl.textContent = '$' + Math.round(totalRepayment).toLocaleString();
    
    console.log('Approval page loaded with:', {
        loanAmount,
        loanTerm,
        monthlyPayment: Math.round(monthlyPayment),
        totalRepayment: Math.round(totalRepayment)
    });
    
    // Create confetti effect
    createConfetti();
});

// Global function for download agreement button
function downloadAgreement() {
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    const loanAmount = parseFloat(applicationData.loanAmount) || 5000;
    const loanTerm = parseInt(applicationData.loanTerm) || 12;
    const annualRate = 0.12;
    const monthlyRate = annualRate / 12;
    
    const monthlyPayment = loanAmount * monthlyRate * Math.pow(1 + monthlyRate, loanTerm) / 
                          (Math.pow(1 + monthlyRate, loanTerm) - 1);
    const totalRepayment = monthlyPayment * loanTerm;
    
    const agreementText = `
LOAN AGREEMENT
==================

Application Number: P{applicationData.applicationId || 'N/A'}
Date: P{new Date().toLocaleDateString('en-US')}

BORROWER INFORMATION:
Name: P{applicationData.fullName || 'N/A'}
Email: P{applicationData.email || 'N/A'}

LOAN DETAILS:
Loan Amount: PP{loanAmount.toLocaleString()}
Interest Rate: P{(annualRate * 100)}% APR
Loan Term: P{loanTerm} months
Monthly Payment: PP{Math.round(monthlyPayment).toLocaleString()}
Total Repayment: PP{Math.round(totalRepayment).toLocaleString()}

PURPOSE: P{applicationData.loanPurpose || 'N/A'}

TERMS AND CONDITIONS:
1. This is a preliminary loan approval document.
2. Final approval is subject to verification of the information you provided.
3. Monthly payments are due on the first of each month.
4. Late fees may apply as per our terms of service.
5. Early repayment is allowed without penalty.

This document is for informational purposes only and is not binding.

Generated by Max it BW Loan
    `;
    
    // Create downloadable file
    const blob = new Blob([agreementText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `loan-agreement-P{applicationData.applicationId || 'draft'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

// Global function for view dashboard
function viewDashboard() {
    alert('Dashboard feature coming soon! You will be able to track your loan status here.');
}

// Global function for social sharing
function shareOnSocial(platform) {
    const applicationData = JSON.parse(sessionStorage.getItem('applicationData') || '{}');
    const loanAmount = parseFloat(applicationData.loanAmount) || 5000;
    const text = `I got approved for a PP{loanAmount.toLocaleString()} loan with Max it BW Loan! 🎉`;
    const url = window.location.origin;
    
    let shareUrl = '';
    
    switch(platform.toLowerCase()) {
        case 'twitter':
            shareUrl = `https://twitter.com/intent/tweet?text=P{encodeURIComponent(text)}&url=P{encodeURIComponent(url)}`;
            break;
        case 'facebook':
            shareUrl = `https://www.facebook.com/sharer/sharer.php?u=P{encodeURIComponent(url)}`;
            break;
        case 'linkedin':
            shareUrl = `https://www.linkedin.com/sharing/share-offsite/?url=P{encodeURIComponent(url)}`;
            break;
        case 'whatsapp':
            shareUrl = `https://wa.me/?text=P{encodeURIComponent(text + ' ' + url)}`;
            break;
    }
    
    if (shareUrl) {
        window.open(shareUrl, '_blank', 'width=600,height=400');
    }
}

// Simple confetti effect - called on page load
function createConfetti() {
    const colors = ['#2563eb', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];
    const confettiContainer = document.querySelector('.approval-card');
    
    if (!confettiContainer) return;
    
    for (let i = 0; i < 50; i++) {
        setTimeout(() => {
            const confetti = document.createElement('div');
            confetti.style.cssText = `
                position: fixed;
                width: 10px;
                height: 10px;
                background: P{colors[Math.floor(Math.random() * colors.length)]};
                left: P{Math.random() * 100}%;
                top: -10px;
                opacity: P{Math.random()};
                transform: rotate(P{Math.random() * 360}deg);
                pointer-events: none;
                z-index: 9999;
            `;
            document.body.appendChild(confetti);
            
            // Animate fall
            let top = -10;
            const speed = Math.random() * 3 + 2;
            const interval = setInterval(() => {
                top += speed;
                confetti.style.top = top + 'px';
                
                if (top > window.innerHeight) {
                    clearInterval(interval);
                    confetti.remove();
                }
            }, 20);
        }, i * 30);
    }
}

// Live Approval Popup JavaScript for Airtel Congo (DRC) - Expanded Data with 4 Hidden Digits
const names = [
    "Jean M.", "Grace K.", "Christian N.", "Marie T.", "Patient B.",
    "David L.", "Sarah M.", "Patrick K.", "Esther N.", "Plamedi B.",
    "Dieumerci S.", "Rachel K.", "Junior M.", "Aime T.", "Jovial P.",
    "Divine K.", "Exaucée N.", "Jonathan B.", "Chantal M.", "Gloire K."
];

const prefixes = ["99", "97", "98", "81", "82", "83"];

function getRandomNumber(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function generateAirtelNumber() {
    const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
    const randomEnd = Math.floor(10 + Math.random() * 90);
    // Hiding the middle 4 digits using ****
    return `+243 ${prefix} **** ${randomEnd}`;
}

function generateApprovalData() {
    return names.map(name => {
        // Random amount between $500 and $50,000
        const amount = getRandomNumber(500, 50000);
        const formattedAmount = "$" + amount.toLocaleString();
        
        // Random time simulation
        const timeOptions = ["Just now", "1 minute ago", "2 minutes ago", "3 minutes ago", "4 minutes ago"];
        const time = timeOptions[Math.floor(Math.random() * timeOptions.length)];

        return {
            name: name,
            phone: generateAirtelNumber(),
            amount: formattedAmount,
            time: time
        };
    });
}

const approvalData = generateApprovalData();

function showRandomApproval() {
    const popup = document.getElementById('popup');
    const popupText = document.getElementById('popup-text');
    const popupTime = document.getElementById('popup-time');
    const popupAvatar = document.getElementById('popup-avatar');

    if (!popup || !popupText || !popupTime || !popupAvatar) return;

    const randomItem = approvalData[Math.floor(Math.random() * approvalData.length)];
    
    popupAvatar.textContent = randomItem.name.charAt(0);
    popupText.innerHTML = `<strong>${randomItem.name}</strong> (${randomItem.phone}) successfully approved <strong>${randomItem.amount}</strong>`;
    popupTime.textContent = randomItem.time;

    popup.classList.add('show');

    setTimeout(() => {
        popup.classList.remove('show');
    }, 4000);
}

// Trigger popup loop
window.addEventListener('DOMContentLoaded', () => {
    setInterval(() => {
        showRandomApproval();
    }, 8000);

    setTimeout(() => {
        showRandomApproval();
    }, 3000);
});
